### ISSUE TITLE
What was your best programming moment?

### ISSUE THREAD

**Issue by arthurvr** [xem/ama#14]

**Comment by xem** [comment]
My best coding memories are related to code-golfing (see #8)

The best moment, I think, happened while we were code-golfing a tiny spreadsheet app.

First, it was a tiny vanillaJS app made by Ondřej Žára: http://jsfiddle.net/ondras/hYfN3/

Then, @aemkei began to golf it in 468b: https://github.com/aemkei/aemkei.github.io/commits/master/sheet/index.html?page=2

And with the help of many great golfers (@subzey, @p01, rlauck) , he managed to take it down to 295b: http://aem1k.com/sheet/

I didn't contribute to it because honestly I could hardly understand what was going on in their code, especially in the first iterations involving many functions, recusrsivity and crazy things like that.

When they couldn't find more tricks to enhance their score, I decide to give it a try, but instead of trying to enhance their version, I prefered restarting it from scratch, with the bare minimum.

For me the simplest thing we could do was a double loop displaying the fields, and each field having two inline event listeners doing all the job: onfocus (to show a formula) and onblur (to compute it).
No legends. (ABCDE/12345), no persistence (localStorage)

I gave it a try and managed to produce a first version in 279b. https://rawgit.com/xem/sheet/5aae731f6a5622150597a103122f03b886721b76/index.html
not bad, but could be better. (for the record, @aemkei's version without legends nor localStorage weighed 272b: http://xem.github.io/sheet/aem1k.html)

I quickly managed to beat it (271b), then I showed it to the team who helped me golf my "remake".

@subzey came up with a great crazy notation: "a[i]+-~j" (instead of "a[i]+(j+1)"). I'm still amazed by this trick.

@p01 made 268, etc.

And at a moment, when I felt blocked, I started fiddling with the code that evals each cell, and out of curiosity, I tried to remove a big part of the code (a "replace()") to see what would happen. I assumed I would see many JS errors in the console, but surprisingly, it worked perfectly, and turned out to be an excellent golfing trick. It was here:
https://github.com/xem/sheet/commit/d9782b9ec6f75abd27ac4d2bafd6445aec8edd49

I didn't understand why it worked at first, and verified many times that it was not a cache problem or something like that, but no, it was it. The app fell from 263b to 249 thanks to an act of serendipity.

If you're curious, I'll try to explain what happens exactly in this code.
a cell can contain a number (ex: 123) or a formula (ex: "=A1+456") or nothing.

BEFORE:
to compute the result of a formula and place it in the cell on blur, we did something like that: `c.value=eval(q.replace("=",""))` (c is the cell, q is the text typed in the cell)
It works for numbers: c.value=eval("123".replace("=","")) => c.value=123
It works for formulas: c.value=eval("=A1+456".replace("=","")) => c.value=eval("A1+456") => c.value=579.
and it works for empty cells.

AFTER:
after removing the replace and moving the eval a little, we had something like that:
`eval("c.value"+q)`
it works for empty cells: eval("c.value"+q) => eval("c.value") => c.value is an empty string, so no error, nothing happens.
It works with formulas: eval("c.value"+q) => eval("c.value" + "=A1+456") => eval("c.value=A1+456") => c.value is correctly set to the result of "A1+456".
And it works with numbers because: eval("c.value"+q) => eval("c.value"+"123") => eval("c.value123") => c.value123 is undefined, but no errors are thrown since we're not trying to get its value, we just mention the attribute "value123" of c, so nothing happens, and the number stays in its cell, and everybody is happy.

This trick is still present in the latest version of my app: http://xem.github.io/sheet/.

and @p01 said "nice move", so it was a great moment.

https://twitter.com/MaximeEuziere/statuses/465417482095050752?tw_i=465417482095050752&tw_e=details&tw_p=archive

PS: the final size is 227b (or 212 if we used ES6). And I made a version with labels and localStorage that fits in 267b (28b less than aemkei's): http://xem.github.io/sheet/xem-labels.html
So my challenge was fullfilled in all possible ways!

Cheers,
:)

**Comment by midaz** [comment]
haha nice
