### ISSUE TITLE
Resources to get started with Code Golfing?

### ISSUE THREAD

**Issue by terkelg** [xem/ama#19]
Can you recommend some good resources for getting started with code golfing?

**Comment by xem** [comment]
Sure !

First, you're invited to join our slack group, where we talk and practise JS code golfing almost everyday, and beginners are welcome too: http://register.jsgolf.club

You can also read our websites:
- http://xem.github.io/articles/ (we just finished our "golfctober" party, it's detailed there)
- http://www.p01.org/
- http://aem1k.com/
- https://cantelope.org/
- http://monometric.net/
- ...

These JS golfing compos are fun to follow too:
http://js1k.com/
http://js13kgames.com/ (+ its resource page: http://js13kgames.github.io/resources/)
https://codegolf.stackexchange.com/ (not only JS)

I can also recommend you this list of all our golfed projects since ~2012:
https://gist.github.com/xem/206db44adbdd09bac424

And this list of JS golfing tricks:
https://github.com/jed/140bytes/wiki/Byte-saving-techniques

Finally, you can learn a lot by reading the detailed source code of golfed  projects, like:
- period1k: https://github.com/codegolf/period1k/blob/gh-pages/golfed.commented.html
- 1karrot: https://github.com/xem/1karrot/blob/gh-pages/index.commented.html
- mini-tetris: https://github.com/veu/mini-tetris/blob/master/src/tetris.js
- tic-tac-toe: https://github.com/ETHproductions/golf/blob/gh-pages/tic-tac-toe/minimal-commented.js
- Unicode slideshow: https://github.com/xem/miniUnicode/blob/gh-pages/js1k.html
- miniShadertoy: https://github.com/xem/MiniShadertoy/blob/gh-pages/js1k.html
- 1kind of magic: https://github.com/xem/1kind-of-magic/blob/gh-pages/commented.html
- if the moon was 1px: https://github.com/xem/if-the-moon-was-1px/blob/gh-pages/commented.js1k.html
- and many more detailed tricks on our websites.

Cheers

**Comment by terkelg** [comment]
Thanks for the amazing and comprehensive answer
