### ISSUE TITLE
Do you spread some "code golfed" chunks in your production code at work ?

### ISSUE THREAD

**Issue by Cycymomo** [xem/ama#6]

**Comment by xem** [comment]
Not exactly: there are tiny codes present on my site or my github that were indeed used as-is in production for my last job and my current job. More than that, most of them were developed to address real-world problems we had at that time at work.

A few examples:
- multiline ellipsis in 5 lines of JS : http://xem.github.io/projects/#ellipsis_en
- a tiny touchable slider : http://xem.github.io/projects/#swipe_en 
- text alignment hacks : http://xem.github.io/projects/#text_alignment_en
- HTML5 video: http://xem.github.io/projects/#video_en
- JS port of stfrtime: https://github.com/xem/strftime

There are also many of my code-golfed projects used very often at work like:
- EscApe
- MiniURI
- events
- charsets
- miniJSPerf
- MiniRegexTester: https://twitter.com/maximeeuziere/status/608674514797494272
- ...

Besides that, very few code-golfing techniques end up in "new" production code, but there are still a few ones that I try to push more and more to save time and increase perfs:
- Using replace and regexp together to accomplish miracles
- ~indexOf(...) instead of indexOf(...) !== -1
- ...

Cheers
